import { useEffect, useRef, useState } from 'react';
import { motion, useScroll, useTransform } from 'framer-motion';
import { ArrowUpRight } from 'lucide-react';

const portrait = 'https://shrug-person-78902957.figma.site/_components/v2/d24c01ad3a56fc65e942a1f501eb73db42d7cf9a/Rectangle_40443.81459862.png';
const decor = {
  moon: 'https://shrug-person-78902957.figma.site/_components/v2/ebb2b8f25d8e24d5f0a5ca8af4c950de81aa2fd7/moon_icon.11395d36.png',
  object: 'https://shrug-person-78902957.figma.site/_components/v2/ebb2b8f25d8e24d5f0a5ca8af4c950de81aa2fd7/p59_1.4659672e.png',
  lego: 'https://shrug-person-78902957.figma.site/_components/v2/ebb2b8f25d8e24d5f0a5ca8af4c950de81aa2fd7/lego_icon-1.703bb594.png',
  group: 'https://shrug-person-78902957.figma.site/_components/v2/ebb2b8f25d8e24d5f0a5ca8af4c950de81aa2fd7/Group_134-1.2e04f3ce.png'
};
const gifs = ['hero-space-voyage-preview-eECLH3Yc','hero-codenest-preview-Cgppc2qV','hero-vex-ventures-preview-BczMFIiw','hero-stellar-ai-v2-preview-DjvxjG3C','hero-asme-preview-B_nGDnTP','hero-transform-data-preview-Cx5OU29N','hero-vitara-preview-Cjz2QYyU','hero-terra-preview-BFjrCr7T','hero-skyelite-preview-DHaZIgUv','hero-aethera-preview-DknSlcTa','hero-designpro-preview-D8c5_een','hero-stellar-ai-preview-D3HL6bw1','hero-xportfolio-preview-D4A8maiC','hero-orbit-web3-preview-BXt4OttD','hero-nexora-preview-cx5HmUgo','hero-evr-ventures-preview-DZxeVFEX','hero-planet-orbit-preview-DWAP8Z1P','hero-new-era-preview-CocuDUm9','hero-wealth-preview-B70idl_u','hero-luminex-preview-CxOP7ce6','hero-celestia-preview-0yO3jXO8'].map(x => `https://motionsites.ai/assets/${x}.gif`);
const projects = [
  ['01','Client','Nextlevel Studio',['hf_20260412_055344_5eff02e0-87a5-41ce-b64f-eb08da8f33db.png','hf_20260412_055431_11d841fd-8b41-46a5-82e4-b04f2407a7d8.png','hf_20260412_055451_e317bf2d-28d4-48cc-86b0-6f72f25b6327.png']],
  ['02','Personal','Aura Brand Identity',['hf_20260412_055654_911201c5-36d9-4bc6-bac7-331adfce159f.png','hf_20260412_055723_5ceda0b8-d9c2-4665-b2e3-83ba19ba76d1.png','hf_20260412_055753_adc5dcbd-a8e6-49c0-b43a-9b030d835cea.png']],
  ['03','Client','Solaris Digital',['hf_20260412_055759_963cfb0b-4bd1-4b0f-9d0a-09bd6cf95b2f.png','hf_20260412_060108_438f781a-9846-4dcc-89ab-c4e6cb830f5b.png','hf_20260412_055818_9d062121-ad7e-46b9-999a-1a6a692ef1ee.png']]
].map(([number, category, name, files]) => ({ number, category, name, files: (files as string[]).map(file => `https://images.higgs.ai/?default=1&output=webp&url=${encodeURIComponent(`https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/${file}`)}&w=1280&q=85`) }));

function FadeIn({ children, delay=0, y=30, x=0, className='' }: any) { return <motion.div className={className} initial={{opacity:0,x,y}} whileInView={{opacity:1,x:0,y:0}} viewport={{once:true,margin:'50px',amount:0}} transition={{duration:.7,delay,ease:[.25,.1,.25,1]}}>{children}</motion.div>; }
function ContactButton() { return <a href="#contact" className="contact-btn">Contact Me</a>; }
function Magnet({ children }: {children: React.ReactNode}) { const ref=useRef<HTMLDivElement>(null); const [pos,setPos]=useState({x:0,y:0}); return <div ref={ref} className="magnet" onMouseMove={e=>{const r=ref.current!.getBoundingClientRect();setPos({x:(e.clientX-(r.left+r.width/2))/3,y:(e.clientY-(r.top+r.height/2))/3})}} onMouseLeave={()=>setPos({x:0,y:0})} style={{transform:`translate3d(${pos.x}px,${pos.y}px,0)`}}>{children}</div>; }
function Marquee() { const ref=useRef<HTMLDivElement>(null); const [offset,setOffset]=useState(0); useEffect(()=>{const on=()=>{if(ref.current)setOffset((window.scrollY-ref.current.offsetTop+innerHeight)*.3)};addEventListener('scroll',on,{passive:true});return()=>removeEventListener('scroll',on)},[]); const tile=(src:string,i:number)=><img key={i} src={src} loading="lazy" className="marquee-tile"/>; return <section ref={ref} className="marquee"><div className="marquee-row" style={{transform:`translateX(${offset-200}px)`}}>{[...gifs.slice(0,11),...gifs.slice(0,11),...gifs.slice(0,11)].map(tile)}</div><div className="marquee-row" style={{transform:`translateX(-${offset-200}px)`}}>{[...gifs.slice(11),...gifs.slice(11),...gifs.slice(11)].map(tile)}</div></section>; }
const aboutText = "With more than five years of experience in design, i focus on branding, web design, and user experience, i truly enjoy working with businesses that aim to stand out and present their best image. Let's build something incredible together!";
function AnimatedText() { const ref=useRef<HTMLParagraphElement>(null); const {scrollYProgress}=useScroll({target:ref,offset:['start 0.8','end 0.2']}); return <p ref={ref} className="animated-text">{aboutText.split('').map((char,i)=><Letter key={i} char={char} index={i} total={aboutText.length} progress={scrollYProgress}/>)}</p>; }
function Letter({char,index,total,progress}:any) { const start=index/total; const end=start+.12; const opacity=useTransform(progress,[start,end],[.2,1]); return <motion.span style={{opacity}}>{char}</motion.span>; }
function About() { return <section id="about" className="about"><FadeIn className="decor moon" delay={.1} x={-80}><img src={decor.moon}/></FadeIn><FadeIn className="decor object" delay={.25} x={-80}><img src={decor.object}/></FadeIn><FadeIn className="decor lego" delay={.15} x={80}><img src={decor.lego}/></FadeIn><FadeIn className="decor group" delay={.3} x={80}><img src={decor.group}/></FadeIn><div className="about-content"><FadeIn><h2 className="hero-heading section-heading">About me</h2></FadeIn><AnimatedText/><FadeIn delay={.3}><ContactButton/></FadeIn></div></section>; }
const services=[['01','3D Modeling','Creation of detailed objects, characters, or environments tailored to specific client needs, ideal for games, products, and visualizations.'],['02','Rendering','High-quality, photorealistic renders that showcase designs with custom lighting, textures, and materials to bring concepts to life.'],['03','Motion Design','Dynamic animations and motion graphics that add energy and storytelling to brands, products, and digital experiences.'],['04','Branding','Crafting cohesive visual identities -- from logos to full brand systems -- that communicate a clear and memorable presence.'],['05','Web Design','Designing clean, modern, and conversion-focused websites with attention to layout, typography, and user experience.']];
function Services(){return <section className="services"><h2 className="dark-heading">Services</h2><div className="service-list">{services.map(([n,name,desc],i)=><FadeIn key={n} delay={i*.1}><div className="service"><strong>{n}</strong><div><h3>{name}</h3><p>{desc}</p></div></div></FadeIn>)}</div></section>}
function ProjectCard({project,index}:{project:any,index:number}){const ref=useRef<HTMLDivElement>(null);const {scrollYProgress}=useScroll({target:ref,offset:['start end','start start']});const scale=useTransform(scrollYProgress,[0,1],[1,1-(projects.length-1-index)*.03]);return <div ref={ref} className="card-wrap" style={{top:`${index*28+96}px`}}><motion.article style={{scale}} className="project-card"><div className="project-top"><span className="project-number">{project.number}</span><div><small>{project.category}</small><h3>{project.name}</h3></div><a href="#contact" className="live-btn">Live Project <ArrowUpRight size={16}/></a></div><div className="project-images"><div><img src={project.files[0]}/><img src={project.files[1]}/></div><img src={project.files[2]}/></div></motion.article></div>}
function Projects(){return <section id="projects" className="projects"><h2 className="hero-heading section-heading">Project</h2>{projects.map((p,i)=><ProjectCard key={p.number} project={p} index={i}/>)}</section>}
function Hero(){return <section className="hero"><FadeIn className="nav"><a href="#about">About</a><a href="#services">Price</a><a href="#projects">Projects</a><a href="#contact">Contact</a></FadeIn><FadeIn delay={.15} y={40} className="heading-wrap"><h1 className="hero-heading">Hi, i&apos;m jack</h1></FadeIn><Magnet><FadeIn delay={.6} y={30} className="portrait"><img src={portrait}/></FadeIn></Magnet><div className="hero-bottom"><FadeIn delay={.35} y={20}><p>a 3d creator driven by crafting striking and unforgettable projects</p></FadeIn><FadeIn delay={.5} y={20}><ContactButton/></FadeIn></div></section>}
export default function App(){return <main><Hero/><Marquee/><About/><section id="services"><Services/></section><Projects/></main>}
